set(_CATKIN_CURRENT_PACKAGE "pytorch_encoding_wrapper")
set(pytorch_encoding_wrapper_VERSION "0.0.0")
set(pytorch_encoding_wrapper_MAINTAINER "Adam Li <adamli@umich.edu>")
set(pytorch_encoding_wrapper_PACKAGE_FORMAT "2")
set(pytorch_encoding_wrapper_BUILD_DEPENDS )
set(pytorch_encoding_wrapper_BUILD_EXPORT_DEPENDS )
set(pytorch_encoding_wrapper_BUILDTOOL_DEPENDS "catkin")
set(pytorch_encoding_wrapper_BUILDTOOL_EXPORT_DEPENDS )
set(pytorch_encoding_wrapper_EXEC_DEPENDS )
set(pytorch_encoding_wrapper_RUN_DEPENDS )
set(pytorch_encoding_wrapper_TEST_DEPENDS )
set(pytorch_encoding_wrapper_DOC_DEPENDS )
set(pytorch_encoding_wrapper_URL_WEBSITE "")
set(pytorch_encoding_wrapper_URL_BUGTRACKER "")
set(pytorch_encoding_wrapper_URL_REPOSITORY "")
set(pytorch_encoding_wrapper_DEPRECATED "")