set(_CATKIN_CURRENT_PACKAGE "sel_map_segmentation")
set(sel_map_segmentation_VERSION "0.0.0")
set(sel_map_segmentation_MAINTAINER "author <author@todo.todo>")
set(sel_map_segmentation_PACKAGE_FORMAT "2")
set(sel_map_segmentation_BUILD_DEPENDS )
set(sel_map_segmentation_BUILD_EXPORT_DEPENDS )
set(sel_map_segmentation_BUILDTOOL_DEPENDS "catkin")
set(sel_map_segmentation_BUILDTOOL_EXPORT_DEPENDS )
set(sel_map_segmentation_EXEC_DEPENDS "rospkg")
set(sel_map_segmentation_RUN_DEPENDS "rospkg")
set(sel_map_segmentation_TEST_DEPENDS )
set(sel_map_segmentation_DOC_DEPENDS )
set(sel_map_segmentation_URL_WEBSITE "")
set(sel_map_segmentation_URL_BUGTRACKER "")
set(sel_map_segmentation_URL_REPOSITORY "")
set(sel_map_segmentation_DEPRECATED "")