set(sel_map_segmentation_SETUP_PY_SETUP_MODULE "distutils.core")
set(sel_map_segmentation_SETUP_PY_VERSION "0.0.0")
set(sel_map_segmentation_SETUP_PY_SCRIPTS "")
set(sel_map_segmentation_SETUP_PY_PACKAGES "sel_map_segmentation")
set(sel_map_segmentation_SETUP_PY_PACKAGE_DIRS "src/sel_map_segmentation")
set(sel_map_segmentation_SETUP_PY_MODULES "")
set(sel_map_segmentation_SETUP_PY_MODULE_DIRS "")