set(_CATKIN_CURRENT_PACKAGE "sel_map")
set(sel_map_VERSION "0.0.0")
set(sel_map_MAINTAINER "adam <adam@todo.todo>")
set(sel_map_PACKAGE_FORMAT "2")
set(sel_map_BUILD_DEPENDS )
set(sel_map_BUILD_EXPORT_DEPENDS )
set(sel_map_BUILDTOOL_DEPENDS "catkin")
set(sel_map_BUILDTOOL_EXPORT_DEPENDS )
set(sel_map_EXEC_DEPENDS "rospy" "sel_map_mesh" "sel_map_segmentation" "sel_map_mapper" "sel_map_utils")
set(sel_map_RUN_DEPENDS "rospy" "sel_map_mesh" "sel_map_segmentation" "sel_map_mapper" "sel_map_utils")
set(sel_map_TEST_DEPENDS )
set(sel_map_DOC_DEPENDS )
set(sel_map_URL_WEBSITE "")
set(sel_map_URL_BUGTRACKER "")
set(sel_map_URL_REPOSITORY "")
set(sel_map_DEPRECATED "")