set(_CATKIN_CURRENT_PACKAGE "sel_map_mesh_publisher")
set(sel_map_mesh_publisher_VERSION "0.0.0")
set(sel_map_mesh_publisher_MAINTAINER "adam <adam@todo.todo>")
set(sel_map_mesh_publisher_PACKAGE_FORMAT "2")
set(sel_map_mesh_publisher_BUILD_DEPENDS "roscpp" "sel_map_mesh" "eigen_340_wrapper")
set(sel_map_mesh_publisher_BUILD_EXPORT_DEPENDS "roscpp" "sel_map_mesh" "eigen_340_wrapper")
set(sel_map_mesh_publisher_BUILDTOOL_DEPENDS "catkin")
set(sel_map_mesh_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(sel_map_mesh_publisher_EXEC_DEPENDS "roscpp" "sel_map_mesh" "eigen_340_wrapper")
set(sel_map_mesh_publisher_RUN_DEPENDS "roscpp" "sel_map_mesh" "eigen_340_wrapper")
set(sel_map_mesh_publisher_TEST_DEPENDS )
set(sel_map_mesh_publisher_DOC_DEPENDS )
set(sel_map_mesh_publisher_URL_WEBSITE "")
set(sel_map_mesh_publisher_URL_BUGTRACKER "")
set(sel_map_mesh_publisher_URL_REPOSITORY "")
set(sel_map_mesh_publisher_DEPRECATED "")