<?xml version="1.0"?>
<package format="2">
  <name>hf_transformers_wrapper</name>
  <version>0.0.1</version>
  <description>Plan to wrap all models accessible with the huggingface transformers library, but currently only wraps Mask2Former.</description>

  <maintainer email="adamli@umich.edu">Adam Li</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

</package>
