set(_CATKIN_CURRENT_PACKAGE "sel_map_mapper")
set(sel_map_mapper_VERSION "0.0.0")
set(sel_map_mapper_MAINTAINER "author <author@todo.todo>")
set(sel_map_mapper_PACKAGE_FORMAT "2")
set(sel_map_mapper_BUILD_DEPENDS )
set(sel_map_mapper_BUILD_EXPORT_DEPENDS )
set(sel_map_mapper_BUILDTOOL_DEPENDS "catkin")
set(sel_map_mapper_BUILDTOOL_EXPORT_DEPENDS )
set(sel_map_mapper_EXEC_DEPENDS "sel_map_mesh" "sel_map_segmentation")
set(sel_map_mapper_RUN_DEPENDS "sel_map_mesh" "sel_map_segmentation")
set(sel_map_mapper_TEST_DEPENDS )
set(sel_map_mapper_DOC_DEPENDS )
set(sel_map_mapper_URL_WEBSITE "")
set(sel_map_mapper_URL_BUGTRACKER "")
set(sel_map_mapper_URL_REPOSITORY "")
set(sel_map_mapper_DEPRECATED "")