set(_CATKIN_CURRENT_PACKAGE "fastscnn_wrapper")
set(fastscnn_wrapper_VERSION "0.0.0")
set(fastscnn_wrapper_MAINTAINER "author <author@todo.todo>")
set(fastscnn_wrapper_PACKAGE_FORMAT "2")
set(fastscnn_wrapper_BUILD_DEPENDS )
set(fastscnn_wrapper_BUILD_EXPORT_DEPENDS )
set(fastscnn_wrapper_BUILDTOOL_DEPENDS "catkin")
set(fastscnn_wrapper_BUILDTOOL_EXPORT_DEPENDS )
set(fastscnn_wrapper_EXEC_DEPENDS )
set(fastscnn_wrapper_RUN_DEPENDS )
set(fastscnn_wrapper_TEST_DEPENDS )
set(fastscnn_wrapper_DOC_DEPENDS )
set(fastscnn_wrapper_URL_WEBSITE "")
set(fastscnn_wrapper_URL_BUGTRACKER "")
set(fastscnn_wrapper_URL_REPOSITORY "")
set(fastscnn_wrapper_DEPRECATED "")