set(_CATKIN_CURRENT_PACKAGE "eigen_340_wrapper")
set(eigen_340_wrapper_VERSION "0.0.0")
set(eigen_340_wrapper_MAINTAINER "author <author@todo.todo>")
set(eigen_340_wrapper_PACKAGE_FORMAT "2")
set(eigen_340_wrapper_BUILD_DEPENDS )
set(eigen_340_wrapper_BUILD_EXPORT_DEPENDS )
set(eigen_340_wrapper_BUILDTOOL_DEPENDS "catkin")
set(eigen_340_wrapper_BUILDTOOL_EXPORT_DEPENDS )
set(eigen_340_wrapper_EXEC_DEPENDS )
set(eigen_340_wrapper_RUN_DEPENDS )
set(eigen_340_wrapper_TEST_DEPENDS )
set(eigen_340_wrapper_DOC_DEPENDS )
set(eigen_340_wrapper_URL_WEBSITE "")
set(eigen_340_wrapper_URL_BUGTRACKER "")
set(eigen_340_wrapper_URL_REPOSITORY "")
set(eigen_340_wrapper_DEPRECATED "")