set(_CATKIN_CURRENT_PACKAGE "sel_map_utils")
set(sel_map_utils_VERSION "0.0.0")
set(sel_map_utils_MAINTAINER "author <author@todo.todo>")
set(sel_map_utils_PACKAGE_FORMAT "2")
set(sel_map_utils_BUILD_DEPENDS )
set(sel_map_utils_BUILD_EXPORT_DEPENDS )
set(sel_map_utils_BUILDTOOL_DEPENDS "catkin")
set(sel_map_utils_BUILDTOOL_EXPORT_DEPENDS )
set(sel_map_utils_EXEC_DEPENDS "rospy")
set(sel_map_utils_RUN_DEPENDS "rospy")
set(sel_map_utils_TEST_DEPENDS )
set(sel_map_utils_DOC_DEPENDS )
set(sel_map_utils_URL_WEBSITE "")
set(sel_map_utils_URL_BUGTRACKER "")
set(sel_map_utils_URL_REPOSITORY "")
set(sel_map_utils_DEPRECATED "")