set(_CATKIN_CURRENT_PACKAGE "sel_map_mesh")
set(sel_map_mesh_VERSION "0.0.0")
set(sel_map_mesh_MAINTAINER "author <author@todo.todo>")
set(sel_map_mesh_PACKAGE_FORMAT "2")
set(sel_map_mesh_BUILD_DEPENDS "eigen_340_wrapper" "nanoflann_132_wrapper")
set(sel_map_mesh_BUILD_EXPORT_DEPENDS "eigen_340_wrapper" "nanoflann_132_wrapper")
set(sel_map_mesh_BUILDTOOL_DEPENDS "catkin")
set(sel_map_mesh_BUILDTOOL_EXPORT_DEPENDS )
set(sel_map_mesh_EXEC_DEPENDS "eigen_340_wrapper" "nanoflann_132_wrapper")
set(sel_map_mesh_RUN_DEPENDS "eigen_340_wrapper" "nanoflann_132_wrapper")
set(sel_map_mesh_TEST_DEPENDS )
set(sel_map_mesh_DOC_DEPENDS )
set(sel_map_mesh_URL_WEBSITE "")
set(sel_map_mesh_URL_BUGTRACKER "")
set(sel_map_mesh_URL_REPOSITORY "")
set(sel_map_mesh_DEPRECATED "")