set(_CATKIN_CURRENT_PACKAGE "nanoflann_132_wrapper")
set(nanoflann_132_wrapper_VERSION "0.0.0")
set(nanoflann_132_wrapper_MAINTAINER "author <author@todo.todo>")
set(nanoflann_132_wrapper_PACKAGE_FORMAT "2")
set(nanoflann_132_wrapper_BUILD_DEPENDS )
set(nanoflann_132_wrapper_BUILD_EXPORT_DEPENDS "eigen_340_wrapper")
set(nanoflann_132_wrapper_BUILDTOOL_DEPENDS "catkin")
set(nanoflann_132_wrapper_BUILDTOOL_EXPORT_DEPENDS )
set(nanoflann_132_wrapper_EXEC_DEPENDS )
set(nanoflann_132_wrapper_RUN_DEPENDS "eigen_340_wrapper")
set(nanoflann_132_wrapper_TEST_DEPENDS )
set(nanoflann_132_wrapper_DOC_DEPENDS )
set(nanoflann_132_wrapper_URL_WEBSITE "")
set(nanoflann_132_wrapper_URL_BUGTRACKER "")
set(nanoflann_132_wrapper_URL_REPOSITORY "")
set(nanoflann_132_wrapper_DEPRECATED "")