set(_CATKIN_CURRENT_PACKAGE "rviz_map_plugin")
set(rviz_map_plugin_VERSION "1.1.0")
set(rviz_map_plugin_MAINTAINER "Sebastian Pütz <spuetz@uos.de>")
set(rviz_map_plugin_PACKAGE_FORMAT "1")
set(rviz_map_plugin_BUILD_DEPENDS "qtbase5-dev" "roscpp" "rviz" "std_msgs" "mesh_msgs" "hdf5_map_io" "ocl-icd-opencl-dev" "opencl-headers")
set(rviz_map_plugin_BUILD_EXPORT_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "roscpp" "rviz" "std_msgs" "mesh_msgs" "hdf5_map_io" "ocl-icd-opencl-dev" "opencl-headers")
set(rviz_map_plugin_BUILDTOOL_DEPENDS "catkin")
set(rviz_map_plugin_BUILDTOOL_EXPORT_DEPENDS )
set(rviz_map_plugin_EXEC_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "roscpp" "rviz" "std_msgs" "mesh_msgs" "hdf5_map_io" "ocl-icd-opencl-dev" "opencl-headers")
set(rviz_map_plugin_RUN_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "roscpp" "rviz" "std_msgs" "mesh_msgs" "hdf5_map_io" "ocl-icd-opencl-dev" "opencl-headers")
set(rviz_map_plugin_TEST_DEPENDS )
set(rviz_map_plugin_DOC_DEPENDS )
set(rviz_map_plugin_URL_WEBSITE "http://ros.org/wiki/mash_tools/rviz_map_plugin")
set(rviz_map_plugin_URL_BUGTRACKER "")
set(rviz_map_plugin_URL_REPOSITORY "")
set(rviz_map_plugin_DEPRECATED "")