set(_CATKIN_CURRENT_PACKAGE "mit_semseg_wrapper")
set(mit_semseg_wrapper_VERSION "0.0.0")
set(mit_semseg_wrapper_MAINTAINER "author <author@todo.todo>")
set(mit_semseg_wrapper_PACKAGE_FORMAT "2")
set(mit_semseg_wrapper_BUILD_DEPENDS )
set(mit_semseg_wrapper_BUILD_EXPORT_DEPENDS )
set(mit_semseg_wrapper_BUILDTOOL_DEPENDS "catkin")
set(mit_semseg_wrapper_BUILDTOOL_EXPORT_DEPENDS )
set(mit_semseg_wrapper_EXEC_DEPENDS )
set(mit_semseg_wrapper_RUN_DEPENDS )
set(mit_semseg_wrapper_TEST_DEPENDS )
set(mit_semseg_wrapper_DOC_DEPENDS )
set(mit_semseg_wrapper_URL_WEBSITE "")
set(mit_semseg_wrapper_URL_BUGTRACKER "")
set(mit_semseg_wrapper_URL_REPOSITORY "")
set(mit_semseg_wrapper_DEPRECATED "")